const DATA = [
  {
    id: 'notfi-0',
    img: 'images/avatar-mark-webber.webp',
    img_alt: 'mark webber image',
    username: 'Mark Webber',
    user_url: '#',
    default_action: 'reacted to your recent post',
    suffix_action: 'My first tournament today!',
    suffix_action_url: '#',
    date: '1m ago',
    read: false,
    message: '',
  },
  {
    id: 'notfi-1',
    img: 'images/avatar-angela-gray.webp',
    img_alt: 'Angela Gray image',
    username: 'Angela Gray',
    user_url: '#',
    default_action: 'followed you',
    suffix_action: '',
    suffix_action_url: '#',
    date: '5m ago',
    read: false,
    message: '',
  },
  {
    id: 'notfi-2',
    img: 'images/avatar-jacob-thompson.webp',
    img_alt: 'Jacob Thompson image',
    username: 'Jacob Thompson',
    user_url: '#',
    default_action: 'has joined your group',
    suffix_action: 'Chess Club',
    suffix_action_url: '#',
    date: '1 day ago',
    read: false,
    message: '',
  },
  {
    id: 'notfi-3',
    img: 'images/avatar-rizky-hasanuddin.webp',
    img_alt: 'Rizky Hasanuddin image',
    username: 'Rizky Hasanuddin',
    user_url: '#',
    default_action: 'sent you a private message',
    suffix_action_url: '#',
    date: '5 days ago',
    read: true,
    message:
      "Hello, thanks for setting up the Chess Club. I've been a member for a few weeks now and I'm already having lots of fun and improving my game.",
  },
  {
    id: 'notfi-4',
    img: 'images/avatar-kimberly-smith.webp',
    img_alt: 'Kimberly Smith image',
    username: 'Kimberly Smith',
    user_url: '#',
    default_action: 'commented on your picture',
    action_src: 'images/image-chess.webp',
    action_src_alt: 'chess image',
    suffix_action: '',
    suffix_action_url: '#',
    date: '1 week ago',
    read: true,
    message: '',
  },

  {
    id: 'notfi-5',
    img: 'images/avatar-nathan-peterson.webp',
    img_alt: 'Nathan Peterson image',
    username: 'Nathan Peterson',
    user_url: '#',
    default_action: 'reacted to your recent post',
    suffix_action: '5 end-game strategies to increase your win rate',
    suffix_action_url: '#',
    date: '2 weeks ago',
    read: true,
    message: '',
  },
  {
    id: 'notfi-6',
    img: 'images/avatar-anna-kim.webp',
    img_alt: 'Anna Kim image',
    username: 'Anna Kim',
    user_url: '#',
    default_action: 'left the group',
    suffix_action: 'Chess Club',
    suffix_action_url: '#',
    date: '2 weeks ago',
    read: true,
    message: '',
  },
];

export { DATA };
